#! /usr/bin/env bash
#
# Serves the site locally via `jekyll serve`
#
# Accepts all the same arguments as `jekyll serve`.

_serve() {
  @go.log INFO "Building and serving site"
  @go.log_command bundle exec jekyll serve "$@"
}

_serve "$@"
